### ISSUE TITLE
Not responding with glcore driver

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/dolphin#100]
Trying to run a gamecube game with the dolphin core while using the glcore video driver will make RA unresponsive on a white screen.
It's just staying there, no crashing, couldn't get a backtrace even using debugbreak.

Same games work fine with the gl driver.

Win7 x64, RA current nightly, nvidia GTX770, i5-3570K

**Comment by klepp0906** [comment]
this ^

was just looking for a place to post about this.  HUGE issue for me as im trying to use a driver that functions with all cores (which rules out vulkan) but still supports slang shaders. 

I thought this was the answer, until I ran up against dolphin, which is unfortunately one of THEE cores for me :(

I deleted the entire config I had set up for it in hopes it was something in there affecting it.  No bueno.

**Comment by Tatsuya79** [comment]
Started with that PR: https://github.com/libretro/RetroArch/pull/8846

@LazyBumHorse

(related one https://github.com/libretro/RetroArch/pull/8848)

**Comment by LazyBumHorse** [comment]
@Tatsuya79 Thanks for the mention, I'll have a look...

> [INFO] [GLCore]: Version: 3.1.0 NVIDIA 430.86.
> [ERROR] [GLCore]: Failed to compile shader: 0(2) : error C0201: unsupported version 310

Okay, that should not happen, glcore should always at least use version 3.2.
Now, is this a problem with the core or with RetroArch...

**Comment by LazyBumHorse** [comment]
> Now, is this a problem with the core or with RetroArch...

It seems the answer is both, kinda.
The dolphin core requests OpenGL version 3.1 Core Profile, which RetroArch gladly gives it.
The glcore video driver then just takes that context and assumes it's version 3.2, causing the crash.
The pull request allows shader compilation for earlier versions, which works around this, but there could still be some issues.

The thing is that RetroArch can't simply force version 3.2, because the OpenGL Core Profile is generally not backwards-compatible (though it could be, I know little about it), so in short, glcore isn't _really_ compatible with dolphin in it's current form.
You can try your luck once the workaround is merged though, it seems it dolphin worked before as well?

One way to properly "fix" this is to have dolphin request OpenGL version 3.2 Core Profile instead, apparently [Beetle PSX had to do this](https://github.com/libretro/beetle-psx-libretro/issues/315) as well.
You could argue that it's about time, 3.2 is 10 years old already.

---

@klepp0906 You can setup RetroArch to use different video drivers for different cores via core overrides, e.g. you create `config/dolphin-emu/dolphin-emu.cfg` with content `video_driver = "vulkan"`, so you can use glcore as default and vulkan for dolphin, allowing for Slang everywhere.
There's a known [instability issue switching between video drivers](https://github.com/libretro/RetroArch/issues/4804) however, you can try, though.

**Comment by klepp0906** [comment]
@LazyBumHorse is that something new(ish)? 

I was under the impression that swapping video drivers required a complete close and restart of retroarch?  With core overrides I could swap from one core to the next both using different video drivers? 

Either way, ill update tonight (seems they take some time to be pushed live usually) and give it a whirl.  I imagine if it (the workaround) worked for you, it will for everyone else.

I'll be glad to jump off this old version and get back to having my mouse hidden when overlays are active and my widgets display in front of the overlays (both which were a concession for the rollback :P)

**Comment by LazyBumHorse** [comment]
@klepp0906 It's not new, I don't think.

> I was under the impression that swapping video drivers required a complete close and restart of retroarch?

_In principle_ you could always change the video driver, load up your core and have it use the new video driver (so you go from glcore in the menu to vulkan in your core for example).
The thing is just that because of the mentioned instability issue you need to restart RetroArch in most cases, so _in practice_ it works differently.

That's why I said you can try, maybe glcore -> vulkan and vulkan -> glcore works, I haven't done much testing on this, but at least the one time I tried, gl or glcore -> vulkan seemed to work.

P.S. I'm actually not sure if there's a difference between changing the video driver in the menu or through a core override, depending on how it's implemented, core overrides might be more stable.

**Comment by klepp0906** [comment]
thanks for the reply (and your work!) 

hopefully i dont need to use vulkan, as it has more issues and less to gain assuming this gets glcore functioning with dolphin anyhow.  Either way, thats a useful bit of knowledge I can file away for later.

I stream RA from my pc to a shield and/or steamlink more often than not, and i know when using vulkan via rpcs3 steam gives me all kinda trouble.  OGL seems to just work, and even if vulkan is more efficient/faster - I have the hardware to make up the difference so the only other thing to gain was access to the slang shaders (which is now moot) and evidently, lower input latency but I play rpgs :P

Thanks again, will keep you posted on how the fix goes when its pushed live :)

**Comment by LazyBumHorse** [comment]
@Tatsuya79 @klepp0906
The pull request has been merged, you can get the nightly on the [buildbot](https://buildbot.libretro.com/nightly/) tomorrow, see how you fare.

**Comment by klepp0906** [comment]
excellent, thank you for the update.  Ill try it first thing in the AM tomorrow and see if its up ;p

**Comment by klepp0906** [comment]
@LazyBumHorse you did it :)  Seems to be loading glcore+dolphin now. hooray.  appreciate it very much!

**Comment by LazyBumHorse** [comment]
So I guess this issue can be closed then... _for now_.

(Nope, no ominous foreboding to be seen here)

**Comment by Tatsuya79** [comment]
Ah indeed, I was the one that opened it.
Let's close it, thanks! :smiley:
