### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by ghost** [libretro/dolphin#276]

**Comment by Nejsplitter** [comment]
I dont know how to open a pull request @bslenul @LibretroAdmin 
I have Observed an issue in dolphin core, it seems retroarchs dolphin core is set to unlimited emulation speed, i have observed sound issues (audio pops, sometimes really subtle) in games because of this and the issue is fixable by editing a games ini in gamesettings folder and putting "[Core] EmulationSpeed = 1.00000000" (normal speed), the emulation speed in standalone dolphin is set to 100% or 1.00000000 (not unlimited) by default and has no sound issues, exposing this setting would make it much easier to set a global default

**Comment by Nejsplitter** [comment]
just realised this can be edited globally using dolphin.ini

**Comment by Nejsplitter** [comment]
just realised this can be edited globally using dolphin.ini

**Comment by Nejsplitter** [comment]
thought i could edit it globally through dolphin.ini but it resets itself to unlimited in the ini each time the core is booted, hopefully it can be exposed as a core option
